Hipblaslt support
ROCm/apex pull request #137
Opened 2024-09-23 15:47 UTC by ramcherukuri

hipBLASLt implementation in fused_dense

2024-10-21 22:08 UTC, pruthvistony requested changes
Please clean up the code.

2024-10-31 05:03 UTC, pruthvistony approved these changes
Initial implementation and code is tested.

2024-10-31 05:03 UTC, merged

2024-11-01 13:49 UTC, lcskrishna commented on setup.py
> +        ext_modules.append(
Indentation is missing.

2024-11-11 17:52 UTC, jithunnair-amd commented on setup.py
> +    device_props = torch.cuda.get_device_properties(0);
This fails in situations where apex is being built as part of a Dockerfile, since GPUs are not visible at that stage.